name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main
      - name: Install formula from source
        run: brew install --build-from-source avalan-ai/avalan/avalan
      - name: Test formula
        run: brew test avalan-ai/avalan/avalan
